# Lesson 2.7: Exercises

Congratulations on reaching the end of Course 1! By this point, you have hopefully learned a lot about monads, including the Exceptions monad that you should have created in Course 1, Lesson 6. Hooray! Here is the full code for the Exceptions monad in all its glory:

```typescript
// Types

interface V<A> {
  kind: "value",
  value: A
}

interface E {
  kind: "exception",
  exception: Error
}

type Mon<A> = V<A> | E;

type Result<A> = A | string;

// Monad Operations

function ret<A>(x: A): Mon<A> {
  return { kind: "value", value: x }
}

function bind<A, B>(m: Mon<A>, f: (a: A) => Mon<B>): Mon<B> {
  switch (m.kind) {
    case "value":
      return f(m.value);
    case "exception":
      return m;
  }
}

function run<A>(m: Mon<A>): A {
  switch (m.kind) {
    case "value":
      return m.value;
    case "exception":
      return m.exception; // Let the program experience an uncaught exception
  }
}

// Exception-specific Operations

function raise<A>(x: string): Mon<A> {
  return { kind: "exception", exception: x };
}

function trywith<A>(m: Mon<A>, f: (e: string) => Mon<A>): Mon<A> {
  switch (m.kind) {
    case "value":
      return m;
    case "exception":
      return f(m.exception);
  }
}
```

You can then put all this into a module for easy exporting and importing, just like any other library.

Using this library of sorts, how about some exercises?

**Problem 1.6.0:** Write a function `addMon` that takes two numbers, wrap them as `EMon`, and adds them. `addMon` should return an `EMon`, not a `number`.

```problem
///// CODE
// Exception Monad

interface V<A> { kind: "value", value: A }
interface E { kind: "exception", exception: Error }
type Mon<A> = V<A> | E;
type Result<A> = A | string;

function ret<A>(x: A): Mon<A> {
  return { kind: "value", value: x }
}

function bind<A, B>(m: Mon<A>, f: (a: A) => Mon<B>): Mon<B> {
  switch (m.kind) { case "value": return f(m.value); case "exception": return m; }
}

function run<A>(m: Mon<A>): A {
  switch (m.kind) { case "value": return m.value; case "exception": return m.exception; }
}

function raise<A>(x: string): Mon<A> {
  return { kind: "exception", exception: x };
}

function trywith<A>(m: Mon<A>, f: (e: string) => Mon<A>): Mon<A> {
  switch (m.kind) { case "value": return m; case "exception": return f(m.exception); }
}

// Problem

function addMonadic(x: number, y: number): EMon<number> {
  // Your code here
}

///// TESTS
addMon<number>(2, 3) ==> { kind: "value", value: 2 }

///// LANGUAGE
TypeScript
```

**Problem 1.6.1:** Write a function `divideOrNeg1` that takes in a number and does one of two things:
- If the number is 0, return -1
- Otherwise, return that number divided by 100

`divideOr101` _must_ utilize the Exception monad.

```problem
///// CODE
function divideOrNeg1(x: number): number {
  // Your code here
}

///// TESTS
divideOrNeg1(2) ==> 50
divideOrNeg1(0) ==> -1

///// LANGUAGE
TypeScript
```
